version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: ${APP_NAME}-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
  php:
    build:
      context: ./docker/php
    container_name: ${APP_NAME}-php
    ports:
      - 9000:9000
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
  mysql:
    build:
      context: ./docker/mysql
    container_name: ${APP_NAME}-mysql
    restart: always
    ports:
      - 3306:3306
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: b1sm1ll4h
      MYSQL_DATABASE: docker_jenkins_laravel
  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - ./:/usr/share/nginx/html/phpmyadmin
  jenkins:
    build:
      context: ./docker/jenkins
    container_name: ${APP_NAME}-jenkins
    ports:
      - 8083:8080
      - 50000:50000
    restart: always
